
services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
    image: sail-8.3/app
    environment:
      WWWUSER: 1000
      WWWGROUP: 1000
      LARAVEL_SAIL: 1
      APP_ENV: local
      APP_DEBUG: 'true'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - pgsql

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - '.:/var/www/html:ro'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - laravel.test
    networks:
      - sail

  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_DB: customer_satisfaction
      POSTGRES_USER: sami
      POSTGRES_PASSWORD: sami
    ports: []
    volumes:
      - 'sail-pgsql:/var/lib/postgresql/data'
    networks:
      - sail

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8090:80"
    depends_on:
      - pgsql
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-pgsql:
    driver: local

