name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build containers
      - name: Build Docker containers
        run: docker compose build

      # 4. Start containers
      - name: Start Docker containers
        run: docker compose up -d

      # 5. Wait for DB and app
      - name: Wait for services
        run: sleep 25

      # 6. Run Laravel tests
      - name: Run Laravel tests
        run: docker compose exec laravel.test php artisan test

      # 7. Push image to Docker Hub (only if tests pass)
      - name: Push Laravel image to Docker Hub
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/laravel-app
          docker tag sail-8.3/app $IMAGE_NAME:latest
          docker push $IMAGE_NAME:latest
    