name: Laravel CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DB_HOST: 127.0.0.1
  DB_PORT: 5432
  DB_DATABASE: customer_satisfaction
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      pgsql:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: ${{ env.DB_DATABASE }}
          POSTGRES_USER: ${{ env.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('backend/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: pdo, pdo_pgsql, mbstring, exif, pcntl, gd, xdebug
          coverage: none

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-scripts
          cp .env.example .env
          php artisan key:generate --force

      - name: Setup test environment
        run: |
          php artisan config:clear
          php artisan migrate --force

      - name: Run Pest tests
        run: ./vendor/bin/pest --stop-on-failure

      - name: Run Pest with coverage (optional)
        run: ./vendor/bin/pest --coverage --min=80

      - name: Run Pest with JUnit output (optional)
        run: ./vendor/bin/pest --log-junit junit.xml

      - name: Upload test results
        if: always() && hashFiles('junit.xml') != ''
        uses: actions/upload-artifact@v4
        with:
          name: pest-test-results
          path: junit.xml

  deploy:
    name: Deploy to GHCR
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      APP_ENV: production
      APP_DEBUG: false
      SWAGGER_ENABLE: ${{ secrets.SWAGGER_ENABLE }}
      L5_SWAGGER_GENERATE_ALWAYS: ${{ secrets.L5_SWAGGER_GENERATE_ALWAYS }}
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_DATABASE: customer_satisfaction
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: ./backend
        run: |
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER/laravel-app

          docker buildx build \
            --platform linux/amd64 \
            --build-arg APP_ENV=$APP_ENV \
            --build-arg APP_DEBUG=$APP_DEBUG \
            --build-arg SWAGGER_ENABLE=$SWAGGER_ENABLE \
            --build-arg L5_SWAGGER_GENERATE_ALWAYS=$L5_SWAGGER_GENERATE_ALWAYS \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:${{ github.sha }} \
            --push .
