name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    env:
      BACKEND_DIR: backend
      APP_Key: ${{ secrets.APP_KEY }}


    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Docker containers
      - name: Build Docker containers
        working-directory: ${{ env.BACKEND_DIR }}
        run: docker compose build

      # 4. Start Docker containers
      - name: Start Docker containers
        working-directory: ${{ env.BACKEND_DIR }}
        run: docker compose up -d

      # 5. Wait for DB and app to be ready
      - name: Wait for services
        run: sleep 25

     # 6. Install dependencies
      - name: Install Laravel dependencies
        working-directory: ${{ env.BACKEND_DIR }}
        run: docker compose run --rm laravel.test composer install --no-interaction --prefer-dist --optimize-autoloader

      # 7. Run Laravel tests
      - name: Run Laravel tests
        working-directory: ${{ env.BACKEND_DIR }}
        run: docker compose run --rm laravel.test php artisan test

